[profile.default]
libs = ["node_modules", "../lib", "../da-contracts/"]
allow_paths = ["../l2-contracts/contracts"]
cache_path = "cache-forge"
fs_permissions = [
    { access = "read", path = "../system-contracts/bootloader/build/artifacts" },
    { access = "read", path = "../system-contracts/artifacts-zk/contracts-preprocessed" },
    { access = "read", path = "../l2-contracts/artifacts-zk/" },
    { access = "read", path = "../l1-contracts/artifacts-zk/" },
    { access = "read", path = "../da-contracts/" },
    { access = "read", path = "./script-config" },
    { access = "read-write", path = "./script-out" },
    { access = "read", path = "./out" },
    { access = "read", path = "./test/foundry/integration/deploy-scripts/script-config/" },
    { access = "read-write", path = "./test/foundry/integration/deploy-scripts/script-out/" },
]
test = "test/foundry"
solc_version = "0.8.24"
evm_version = "cancun"
ignored_error_codes = ["missing-receive-ether", "code-size"]
ignored_warnings_from = ["test", "contracts/dev-contracts"]
remappings = [
    "forge-std/=../lib/forge-std/src/",
    "murky/=../lib/murky/src/",
    "foundry-test/=test/foundry/",
    "l2-contracts/=../l2-contracts/contracts/",
    "da-contracts/=../da-contracts/contracts/"
]
