[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
test = "test/foundry"
solc_version = "0.8.20"
cache_path = "cache-forge"
via_ir = true
evm_version = "paris"
ignored_error_codes = ["missing-receive-ether", "code-size"]
ignored_warnings_from = ["test", "contracts/dev-contracts"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "foundry-test/=test/foundry/",
]
fs_permissions = [
    { access = "read", path = "zkout" },
]

